package com.cloud.ui;

import com.cloud.tasks.GenerateJavaDocProcess;
import com.intellij.openapi.progress.BackgroundTaskQueue;
import com.intellij.openapi.project.Project;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.kitt.util.DocUtil;

import javax.swing.*;
import java.awt.*;

/**
 * @Author Xps13
 * @Description //TODO
 * @Date 2019/5/29 14:08
 */
public class ApisPanel {
    private JTabbedPane versionPane;
    private JPanel UI;

    public ApisPanel(String moduleName, Project project) {

        DocUtil docUtil = new DocUtil().setVersionPane(versionPane);

        new BackgroundTaskQueue(project, "正在分析文档...").run(new GenerateJavaDocProcess(project, "正在分析文档...", moduleName, docUtil));

    }

    public JPanel getUI() {
        return UI;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        UI = new JPanel();
        UI.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        versionPane = new JTabbedPane();
        versionPane.setTabPlacement(2);
        UI.add(versionPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        versionPane.addTab("正在生成...", panel1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return UI;
    }

}
