package com.cloud.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * @Author Xps13
 * @Description //TODO
 * @Date 2019/5/16 11:47
 */
public class PanelTabWithClose {
    private JPanel ui;
    private JLabel close;
    private JLabel theText;

    public PanelTabWithClose(String titileText, JTabbedPane tabbedPane, JComponent panel) {
        this.theText.setText(titileText);
        this.close.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getButton() == 1) {
                    tabbedPane.remove(panel);
                }
            }
        });
    }

    public JPanel getUi() {
        return ui;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ui = new JPanel();
        ui.setLayout(new BorderLayout(0, 0));
        close = new JLabel();
        close.setHorizontalAlignment(2);
        close.setIcon(new ImageIcon(getClass().getResource("/icons/x_alt_24px.png")));
        close.setOpaque(true);
        close.setText("");
        close.setToolTipText("关闭标签页");
        ui.add(close, BorderLayout.EAST);
        theText = new JLabel();
        theText.setText("");
        ui.add(theText, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ui;
    }

}
